In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [3]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [4]:
B

array([3, 4, 5])

In [5]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [6]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [7]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [8]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [9]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [10]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

In [11]:
import numpy as np

In [12]:
x = np.array([i for i in range(10)])

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [15]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [16]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [19]:
arr=np.array([[4,3,2],[10,1,0],[5,8,24]])

In [20]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [21]:
np.amin(arr)

np.int32(0)

In [22]:
np.amin(arr,axis=0)

array([4, 1, 0])

In [23]:
np.amin(arr,axis=1)

array([2, 0, 5])

In [24]:
np.max(arr)

np.int32(24)

In [25]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [26]:
np.amax(arr,axis=1)

array([ 4, 10, 24])

In [27]:
np.median(arr)

np.float64(4.0)

In [28]:
np.mean(arr)

np.float64(6.333333333333333)

In [29]:
np.std(arr)

np.float64(6.944222218666553)

In [30]:
np.var(arr)

np.float64(48.22222222222222)

In [32]:
np.percentile(arr,50)

np.float64(4.0)

In [33]:
deg = np.array([0,30,45,60,90])

In [34]:
np.sin(deg*np.pi/100)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [35]:
np.cos(deg*np.pi/100)

array([ 1.        ,  0.58778525,  0.15643447, -0.30901699, -0.95105652])

In [36]:
np.tan(deg*np.pi/100)

array([ 0.        ,  1.37638192,  6.31375151, -3.07768354, -0.3249197 ])

In [37]:
'''
arcsin
arccos
arctan
'''

'\narcsin\narccos\narctan\n'

In [38]:
arr = np.array([0.1,0.8,-2.2,-9.87])

In [39]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [40]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])